export default [
  {
    "login": "Ankit626",
    "id": 79766802,
    "node_id": "MDQ6VXNlcjc5NzY2ODAy",
    "avatar_url": "https://avatars.githubusercontent.com/u/79766802?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Ankit626",
    "html_url": "https://github.com/Ankit626",
    "followers_url": "https://api.github.com/users/Ankit626/followers",
    "following_url": "https://api.github.com/users/Ankit626/following{/other_user}",
    "gists_url": "https://api.github.com/users/Ankit626/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Ankit626/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Ankit626/subscriptions",
    "organizations_url": "https://api.github.com/users/Ankit626/orgs",
    "repos_url": "https://api.github.com/users/Ankit626/repos",
    "events_url": "https://api.github.com/users/Ankit626/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Ankit626/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "Monu7890",
    "id": 79953467,
    "node_id": "MDQ6VXNlcjc5OTUzNDY3",
    "avatar_url": "https://avatars.githubusercontent.com/u/79953467?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Monu7890",
    "html_url": "https://github.com/Monu7890",
    "followers_url": "https://api.github.com/users/Monu7890/followers",
    "following_url": "https://api.github.com/users/Monu7890/following{/other_user}",
    "gists_url": "https://api.github.com/users/Monu7890/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Monu7890/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Monu7890/subscriptions",
    "organizations_url": "https://api.github.com/users/Monu7890/orgs",
    "repos_url": "https://api.github.com/users/Monu7890/repos",
    "events_url": "https://api.github.com/users/Monu7890/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Monu7890/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "Rahul7656",
    "id": 79955003,
    "node_id": "MDQ6VXNlcjc5OTU1MDAz",
    "avatar_url": "https://avatars.githubusercontent.com/u/79955003?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Rahul7656",
    "html_url": "https://github.com/Rahul7656",
    "followers_url": "https://api.github.com/users/Rahul7656/followers",
    "following_url": "https://api.github.com/users/Rahul7656/following{/other_user}",
    "gists_url": "https://api.github.com/users/Rahul7656/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Rahul7656/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Rahul7656/subscriptions",
    "organizations_url": "https://api.github.com/users/Rahul7656/orgs",
    "repos_url": "https://api.github.com/users/Rahul7656/repos",
    "events_url": "https://api.github.com/users/Rahul7656/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Rahul7656/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "ParasSingh143",
    "id": 79955732,
    "node_id": "MDQ6VXNlcjc5OTU1NzMy",
    "avatar_url": "https://avatars.githubusercontent.com/u/79955732?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ParasSingh143",
    "html_url": "https://github.com/ParasSingh143",
    "followers_url": "https://api.github.com/users/ParasSingh143/followers",
    "following_url": "https://api.github.com/users/ParasSingh143/following{/other_user}",
    "gists_url": "https://api.github.com/users/ParasSingh143/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ParasSingh143/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ParasSingh143/subscriptions",
    "organizations_url": "https://api.github.com/users/ParasSingh143/orgs",
    "repos_url": "https://api.github.com/users/ParasSingh143/repos",
    "events_url": "https://api.github.com/users/ParasSingh143/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ParasSingh143/received_events",
    "type": "User",
    "site_admin": false
  }
]