export default {
  "login": "lakhan5555",
  "id": 62960598,
  "node_id": "MDQ6VXNlcjYyOTYwNTk4",
  "avatar_url": "https://avatars.githubusercontent.com/u/62960598?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/lakhan5555",
  "html_url": "https://github.com/lakhan5555",
  "followers_url": "https://api.github.com/users/lakhan5555/followers",
  "following_url": "https://api.github.com/users/lakhan5555/following{/other_user}",
  "gists_url": "https://api.github.com/users/lakhan5555/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/lakhan5555/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/lakhan5555/subscriptions",
  "organizations_url": "https://api.github.com/users/lakhan5555/orgs",
  "repos_url": "https://api.github.com/users/lakhan5555/repos",
  "events_url": "https://api.github.com/users/lakhan5555/events{/privacy}",
  "received_events_url": "https://api.github.com/users/lakhan5555/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Ram Lakhan Singh",
  "company": null,
  "blog": "http://ramlakhansingh.pythonanywhere.com/",
  "location": "Arrah",
  "email": null,
  "hireable": null,
  "bio": "A Full Stack Web Developer. Work with React and Django",
  "twitter_username": "lakhan5555",
  "public_repos": 15,
  "public_gists": 0,
  "followers": 1,
  "following": 1,
  "created_at": "2020-03-31T18:54:31Z",
  "updated_at": "2021-02-27T14:56:49Z"
}